version: "3"

services:
  head:
    image: mminutoli/inf-max-dev-env
    user: root
    entrypoint: [ "/usr/sbin/sshd", "-D" ]
    volumes:
      - ..:/home/mpi/ripples
    ports:
      - 22
    networks:
      - net
  worker:
    image: mminutoli/inf-max-dev-env
    user: root
    entrypoint: [ "/usr/sbin/sshd", "-D" ]
    volumes:
      - ..:/home/mpi/ripples
    ports:
      - 22
    networks:
      - net

networks:
  net:
